version: '3.7'

networks:
  monitor-net:
    driver: bridge

services:
  nats-1:
    image: nats:2.10.10
    container_name: n1
    restart: always
    command: -c /etc/nats/nats.conf
    ports:
      - "4222:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port
    volumes:
      - ./nats1.conf:/etc/nats/nats.conf
      - ./storage/jetstream-cluster/n1:/data
    networks:
      - monitor-net

  nats-2:
    image: nats:2.10.10
    container_name: n2
    restart: always
    command: -c /etc/nats/nats.conf
    ports:
      - ":4222" # client port
      - ":6222" # cluster port
#      - "8222:8222" # monitoring port
    volumes:
      - ./nats2.conf:/etc/nats/nats.conf
      - ./storage/jetstream-cluster/n2:/data
    networks:
      - monitor-net

  nats-3:
    image: nats:2.10.10
    container_name: n3
    restart: always
    command: -c /etc/nats/nats.conf
    ports:
      - ":4222" # client port
      - ":6222" # cluster port
#      - "8222:8222" # monitoring port
    volumes:
      - ./nats3.conf:/etc/nats/nats.conf
      - ./storage/jetstream-cluster/n3:/data
    networks:
      - monitor-net


  exporter:
    image: natsio/prometheus-nats-exporter
    container_name: nats-exporter
    restart: always
    command: 
      - -connz_detailed
      - -jsz=all
      - -routez
      - -subz
      - -varz
      - -prefix=nats
      - -use_internal_server_id
      - http://n1:8222/
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "nats-monitoring"
    ports:
      - "7777:7777" # client por     
    depends_on:
      - nats-1

  surveyor:
    image: natsio/nats-surveyor
    container_name: nats-surveyor
    restart: always
    volumes:
      - ./observations:/observations
      - $JETSTREAM_STORAGE:/data
    command: |
      --count ${NATS_SURVEYOR_SERVER_COUNT} -s ${NATS_SURVEYOR_SERVERS}
      --accounts --observe /observations --jetstream /data
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "nats-monitoring"


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: "root"
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - $PROMETHEUS_STORAGE:/usr/local/share/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/usr/local/share/prometheus
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "nats-monitoring"
    ports:
      - "127.0.0.1:9090:9090"
    depends_on:
      - surveyor
      - exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "127.0.0.1:8055:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "nats-monitoring"
    depends_on:
      - prometheus
